import type { ProductBacklog } from "@/domain/entities/product-backlog";

export const initialData: ProductBacklog[] = [
    {
        id: "task-1",
        projectId: "project-1",
        point: 5,
        sprintId: "sprint-2",
        productGoalId: "goal-1",
        title: "Implement user authentication",
        priority: "HIGH",
        status: "TODO",
        creatorId: "user-1",
        assigneeId: "user-2",
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: "task-2",
        projectId: "project-1",
        point: 3,
        sprintId: "sprint-1",
        productGoalId: "goal-1",
        title: "Design dashboard layout",
        priority: "MEDIUM",
        status: "TODO",
        creatorId: "user-1",
        assigneeId: null,
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: "task-3",
        projectId: "project-1",
        point: 8,
        sprintId: "sprint-1",
        productGoalId: "goal-2",
        title: "API integration",
        priority: "HIGH",
        status: "INPROGRESS",
        creatorId: "user-1",
        assigneeId: "user-3",
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: "task-4",
        projectId: "project-1",
        point: 2,
        sprintId: "sprint-1",
        productGoalId: "goal-2",
        title: "Fix navigation bug",
        priority: "LOW",
        status: "INPROGRESS",
        creatorId: "user-2",
        assigneeId: "user-2",
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: "task-5",
        projectId: "project-1",
        point: 1,
        sprintId: "sprint-1",
        productGoalId: "goal-3",
        title: "Update documentation",
        priority: "MEDIUM",
        status: "DONE",
        creatorId: "user-3",
        assigneeId: "user-1",
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
]
